services:
  backend:
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: .env
