services:
  backend:
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: python ./app/main.py
    environment:
      dbhostname: db
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: .env
