services:
  backend:
    build: ./backend/
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./backend/app:/erdos/app:ro
      - ./models:/erdos/models:ro
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
